// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CallLog struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CallerNumber   string             `json:"caller_number"`
	CallDuration   int32              `json:"call_duration"`
	RecordingUrl   pgtype.Text        `json:"recording_url"`
	Transcript     pgtype.Text        `json:"transcript"`
	SentimentScore pgtype.Float8      `json:"sentiment_score"`
	RiskScore      pgtype.Float8      `json:"risk_score"`
	Flagged        bool               `json:"flagged"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CallLogsTag struct {
	CallLogID uuid.UUID `json:"call_log_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

type Tag struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Queries provides database operations
type Queries struct {
	db DBTX
}
