// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTagToCallLog(ctx context.Context, arg AddTagToCallLogParams) error
	CreateCallLog(ctx context.Context, arg CreateCallLogParams) (CallLog, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCallLog(ctx context.Context, id uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCallLogByID(ctx context.Context, id uuid.UUID) (CallLog, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTagsForCallLog(ctx context.Context, callLogID uuid.UUID) ([]Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCallLogs(ctx context.Context, arg ListCallLogsParams) ([]CallLog, error)
	ListCallLogsByUserID(ctx context.Context, arg ListCallLogsByUserIDParams) ([]CallLog, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveTagFromCallLog(ctx context.Context, arg RemoveTagFromCallLogParams) error
	UpdateCallLog(ctx context.Context, arg UpdateCallLogParams) (CallLog, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
